library(devtools)
load_all()
smd = data_extraction_sheet(measure="d", type_of_measure = "natural")
rio::export(smd, "web/data_extraction/smd.csv")
md = data_extraction_sheet(measure="md", type_of_measure = "natural")
rio::export(md, "web/data_extraction/md.csv")
var = data_extraction_sheet(measure="logvr", type_of_measure = "natural")
rio::export(var, "web/data_extraction/var.csv")
cor = data_extraction_sheet(measure="r", type_of_measure = "natural")
rio::export(cor, "web/data_extraction/cor.csv")
or = data_extraction_sheet(measure="or", type_of_measure = "natural")
rio::export(or, "web/data_extraction/or.csv")
rr = data_extraction_sheet(measure="rr", type_of_measure = "natural")
rio::export(rr, "web/data_extraction/rr.csv")
nnt = data_extraction_sheet(measure="nnt", type_of_measure = "natural")
rio::export(nnt, "web/data_extraction/nnt.csv")
