library(devtools)
load_all()
smd = data_extraction_sheet(measure="d", type_of_measure = "natural+converted")
rio::export(smd, "web/data_extraction/smd.xlsx")
md = data_extraction_sheet(measure="md", type_of_measure = "natural+converted")
rio::export(md, "web/data_extraction/md.xlsx", overwrite=TRUE)
var = data_extraction_sheet(measure="logvr", type_of_measure = "natural+converted")
rio::export(var, "web/data_extraction/var.xlsx", overwrite=TRUE)
cor = data_extraction_sheet(measure="r", type_of_measure = "natural+converted")
rio::export(cor, "web/data_extraction/cor.xlsx", overwrite=TRUE)
or = data_extraction_sheet(measure="or", type_of_measure = "natural+converted")
rio::export(or, "web/data_extraction/or.xlsx", overwrite=TRUE)
rr = data_extraction_sheet(measure="rr", type_of_measure = "natural+converted")
rio::export(rr, "web/data_extraction/rr.xlsx", overwrite=TRUE)
nnt = data_extraction_sheet(measure="nnt", type_of_measure = "natural+converted")
rio::export(nnt, "web/data_extraction/nnt.xlsx", overwrite=TRUE)
